/* Autogenerated with kurento-module-creator */

#ifndef __VISUALIZER_OPENCV_IMPL_HPP__
#define __VISUALIZER_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "Visualizer.hpp"
#include <EventHandler.hpp>
#include <VPDetector.hpp>
#include <tinyxml2.h>

namespace kurento
{
namespace module
{
namespace visualizer
{

class VisualizerOpenCVImpl : public virtual OpenCVProcess
{

private:

	//Drawing
	std::vector<int> color;
	int method;
	std::string text;

public:

  VisualizerOpenCVImpl ();

  virtual ~VisualizerOpenCVImpl ();

  virtual void process (cv::Mat &mat);

  void setConfiguration(const std::string &file);

};

} /* visualizer */
} /* module */
} /* kurento */

#endif /*  __VISUALIZER_OPENCV_IMPL_HPP__ */
