/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <VisualizerImplFactory.hpp>
#include "VisualizerImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include "MediaPipelineImpl.hpp"

#define GST_CAT_DEFAULT kurento_visualizer_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoVisualizerImpl"

namespace kurento
{
namespace module
{
namespace visualizer
{

VisualizerImpl::VisualizerImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) : OpenCVFilterImpl (config, std::dynamic_pointer_cast<MediaPipelineImpl> (mediaPipeline) )

{
}

void VisualizerImpl::setConfiguration (const std::string &file)
{
  VisualizerOpenCVImpl::setConfiguration (file);
}

MediaObjectImpl *
VisualizerImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new VisualizerImpl (config, mediaPipeline);
}

VisualizerImpl::StaticConstructor VisualizerImpl::staticConstructor;

VisualizerImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* visualizer */
} /* module */
} /* kurento */
