/* Autogenerated with kurento-module-creator */

#ifndef __OUTDOOR_PEOPLE_DETECTOR_OPENCV_IMPL_HPP__
#define __OUTDOOR_PEOPLE_DETECTOR_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "OutdoorPeopleDetector.hpp"
#include <EventHandler.hpp>
#include <cmath>
#include <string>
#include <sstream>
#include <VPDetector.hpp>
#include <tinyxml2.h>

namespace kurento
{
namespace module
{
namespace outdoorpeopledetector
{

class OutdoorPeopleDetectorOpenCVImpl : public virtual OpenCVProcess
{

private:

	//Classification variables
	Classifier classifier_;
	float aspectNormalizer;
	bool datasetLoaded;

	//Classification parameters
	std::vector<float> params;

	//Drawing
	std::vector<int> color;
	int method;
	std::string text;

public:

  OutdoorPeopleDetectorOpenCVImpl ();

  virtual ~OutdoorPeopleDetectorOpenCVImpl () ;

  virtual void process (cv::Mat &mat);

  void setDB(const std::string &db);
  void setConfiguration(const std::string &file);

};

} /* outdoorpeopledetector */
} /* module */
} /* kurento */

#endif /*  __OUTDOOR_PEOPLE_DETECTOR_OPENCV_IMPL_HPP__ */
