/* Autogenerated with kurento-module-creator */

#ifndef __VISUALIZER_HPP__
#define __VISUALIZER_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "OpenCVFilter.hpp"

namespace kurento
{
namespace module
{
namespace visualizer
{
class Visualizer;
} /* visualizer */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::visualizer::Visualizer> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace visualizer
{
class Visualizer : public virtual OpenCVFilter
{

public:
  Visualizer () {};
  virtual ~Visualizer () {};

  virtual void setConfiguration (const std::string &file) = 0;

  virtual const std::string& getType () const;
  virtual const std::string& getQualifiedType () const;
  virtual const std::string& getModule () const;
  virtual const std::vector<std::string>& getHierarchy () const;

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* visualizer */
} /* module */
} /* kurento */

#endif /*  __VISUALIZER_HPP__ */
