/* Autogenerated with kurento-module-creator */

#include "VisualizerImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace visualizer
{

void dummyVisualizer ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<Visualizer> object;

    s.SerializeNVP (object);
  }
}

} /* visualizer */
} /* module */
} /* kurento */
