/* Autogenerated with kurento-module-creator */

#include "SubsenseImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace subsense
{

void dummySubsense ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<Subsense> object;

    s.SerializeNVP (object);
  }
}

} /* subsense */
} /* module */
} /* kurento */
