/* Autogenerated with kurento-module-creator */

#ifndef __SUBSENSE_IMPL_FACTORY_HPP__
#define __SUBSENSE_IMPL_FACTORY_HPP__

#include "SubsenseImpl.hpp"
#include "OpenCVFilterImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace subsense
{

class SubsenseImplFactory : public virtual OpenCVFilterImplFactory
{
public:
  SubsenseImplFactory () {};

  virtual std::string getName () const {
    return "Subsense";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* subsense */
} /* module */
} /* kurento */

#endif /*  __SUBSENSE_IMPL_FACTORY_HPP__ */