/* Autogenerated with kurento-module-creator */

#ifndef __OUTDOOR_PEOPLE_DETECTOR_IMPL_HPP__
#define __OUTDOOR_PEOPLE_DETECTOR_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "OutdoorPeopleDetector.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "OutdoorPeopleDetectorOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace outdoorpeopledetector
{
class OutdoorPeopleDetectorImpl;
} /* outdoorpeopledetector */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::outdoorpeopledetector::OutdoorPeopleDetectorImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace outdoorpeopledetector
{

class OutdoorPeopleDetectorImpl : public OpenCVFilterImpl, public virtual OutdoorPeopleDetector, public virtual OutdoorPeopleDetectorOpenCVImpl
{

public:

  OutdoorPeopleDetectorImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~OutdoorPeopleDetectorImpl () {};

  void setDB(const std::string &db);
  void setConfiguration(const std::string &file);

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* outdoorpeopledetector */
} /* module */
} /* kurento */

#endif /*  __OUTDOOR_PEOPLE_DETECTOR_IMPL_HPP__ */
