/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "IndoorPeopleDetectorImpl.hpp"
#include "IndoorPeopleDetectorImplFactory.hpp"
#include "IndoorPeopleDetectorInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{
namespace module
{
namespace indoorpeopledetector
{

MediaObjectImpl *IndoorPeopleDetectorImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  IndoorPeopleDetectorConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
IndoorPeopleDetectorImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "setDB") {
    kurento::JsonSerializer s (false);
    IndoorPeopleDetectorMethodSetDB method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<IndoorPeopleDetector> (obj) );
    return;
  }

  if (methodName == "setConfiguration") {
    kurento::JsonSerializer s (false);
    IndoorPeopleDetectorMethodSetConfiguration method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<IndoorPeopleDetector> (obj) );
    return;
  }

  OpenCVFilterImpl::invoke (obj, methodName, params, response);
}

bool
IndoorPeopleDetectorImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return OpenCVFilterImpl::connect (eventType, handler);
}

void
IndoorPeopleDetectorImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'IndoorPeopleDetectorImpl' cannot be deserialized as an object");
  }
}
} /* indoorpeopledetector */
} /* module */
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::module::indoorpeopledetector::IndoorPeopleDetectorImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::module::indoorpeopledetector::IndoorPeopleDetectorImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::module::indoorpeopledetector::IndoorPeopleDetectorImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::module::indoorpeopledetector::IndoorPeopleDetector> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::module::indoorpeopledetector::IndoorPeopleDetectorImpl> aux = std::dynamic_pointer_cast<kurento::module::indoorpeopledetector::IndoorPeopleDetectorImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::module::indoorpeopledetector::IndoorPeopleDetector> (aux);
}

} /* kurento */