/* Autogenerated with kurento-module-creator */

#include "OutdoorPeopleDetector.hpp"
#include <mutex>

namespace kurento
{
namespace module
{
namespace outdoorpeopledetector
{

static std::vector<std::string> hierarchyOutdoorPeopleDetector;
std::once_flag initFlagOutdoorPeopleDetector;

static void
initHierarchy ()
{
  hierarchyOutdoorPeopleDetector.push_back("kurento.OpenCVFilter");
  hierarchyOutdoorPeopleDetector.push_back("kurento.Filter");
  hierarchyOutdoorPeopleDetector.push_back("kurento.MediaElement");
  hierarchyOutdoorPeopleDetector.push_back("kurento.MediaObject");
}

const std::vector<std::string> &
OutdoorPeopleDetector::getHierarchy () const
{
  std::call_once (initFlagOutdoorPeopleDetector,initHierarchy);
  return hierarchyOutdoorPeopleDetector;
}

const std::string&
OutdoorPeopleDetector::getType () const {
  static std::string typeName = "OutdoorPeopleDetector";

  return typeName;
}

const std::string&
OutdoorPeopleDetector::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
OutdoorPeopleDetector::getModule () const {
  static std::string moduleName =  "outdoorpeopledetector";

  return moduleName;
}

} /* outdoorpeopledetector */
} /* module */
} /* kurento */
