/* Autogenerated with kurento-module-creator */

#ifndef __VISUALIZER_IMPL_FACTORY_HPP__
#define __VISUALIZER_IMPL_FACTORY_HPP__

#include "VisualizerImpl.hpp"
#include "OpenCVFilterImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace visualizer
{

class VisualizerImplFactory : public virtual OpenCVFilterImplFactory
{
public:
  VisualizerImplFactory () {};

  virtual std::string getName () const {
    return "Visualizer";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* visualizer */
} /* module */
} /* kurento */

#endif /*  __VISUALIZER_IMPL_FACTORY_HPP__ */