/* Autogenerated with kurento-module-creator */

#ifndef __RECORDER_BY_MOVEMENT_HPP__
#define __RECORDER_BY_MOVEMENT_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "OpenCVFilter.hpp"

namespace kurento
{
namespace module
{
namespace recorderbymovement
{
class RecorderByMovement;
} /* recorderbymovement */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::recorderbymovement::RecorderByMovement> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace recorderbymovement
{
class RecorderByMovement : public virtual OpenCVFilter
{

public:
  RecorderByMovement () {};
  virtual ~RecorderByMovement () {};

  virtual void loadConfig (const std::string &file) = 0;

  virtual const std::string& getType () const;
  virtual const std::string& getQualifiedType () const;
  virtual const std::string& getModule () const;
  virtual const std::vector<std::string>& getHierarchy () const;

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* recorderbymovement */
} /* module */
} /* kurento */

#endif /*  __RECORDER_BY_MOVEMENT_HPP__ */
