# - Try to find KMSOUTDOORPEOPLEDETECTOR library

#=============================================================================
# Copyright 2014 Kurento
#
#=============================================================================

set(PACKAGE_VERSION "0.0.1~0.g93ece1e")
set(KMSOUTDOORPEOPLEDETECTOR_VERSION ${PACKAGE_VERSION})

message (STATUS "Looking for KMSOUTDOORPEOPLEDETECTOR: 0.0.1~0.g93ece1e")

include (GenericFind)

generic_find (
  REQUIRED
  LIBNAME KMSCORE
  VERSION ^6.0.0
)

generic_find (
  REQUIRED
  LIBNAME KMSELEMENTS
  VERSION ^6.0.0
)

generic_find (
  REQUIRED
  LIBNAME KMSFILTERS
  VERSION ^6.0.0
)

set (REQUIRED_VARS
  KMSOUTDOORPEOPLEDETECTOR_VERSION
  KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS
  KMSOUTDOORPEOPLEDETECTOR_LIBRARY
  KMSOUTDOORPEOPLEDETECTOR_LIBRARIES
)

set (KMSOUTDOORPEOPLEDETECTOR_BINARY_DIR_PREFIX "build" CACHE PATH "Path prefix used to look for binary files")
set (KMSOUTDOORPEOPLEDETECTOR_SOURCE_DIR_PREFIX "" CACHE PATH "Path prefix used to look for source files")

set(KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS
  ${KMSCORE_INCLUDE_DIRS}
  ${KMSELEMENTS_INCLUDE_DIRS}
  ${KMSFILTERS_INCLUDE_DIRS}
)

if (NOT "OutdoorPeopleDetector.hpp OutdoorPeopleDetectorInternal.hpp" STREQUAL " ")
  if (TARGET kmsoutdoorpeopledetectorinterface)
    set (KMSOUTDOORPEOPLEDETECTOR_INTERFACE_INCLUDE_DIR "${KMSOUTDOORPEOPLEDETECTOR_BINARY_DIR_PREFIX}/src/server/interface/generated-cpp")
  else ()
    find_path(KMSOUTDOORPEOPLEDETECTOR_INTERFACE_INCLUDE_DIR
      NAMES
        OutdoorPeopleDetector.hpp
        OutdoorPeopleDetectorInternal.hpp
      PATH_SUFFIXES
        ${KMSOUTDOORPEOPLEDETECTOR_BINARY_DIR_PREFIX}/src/server/interface/generated-cpp
        kurento/modules/outdoorpeopledetector
    )
  endif ()

  list (APPEND KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS ${KMSOUTDOORPEOPLEDETECTOR_INTERFACE_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOUTDOORPEOPLEDETECTOR_INTERFACE_INCLUDE_DIR)
endif ()

if (NOT "OutdoorPeopleDetectorImplFactory.hpp" STREQUAL "")
  if (TARGET kmsoutdoorpeopledetectorimpl)
    set (KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_INTERNAL_INCLUDE_DIR "${KMSOUTDOORPEOPLEDETECTOR_BINARY_DIR_PREFIX}/src/server/implementation/generated-cpp")
  else ()
    find_path(KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_INTERNAL_INCLUDE_DIR
      NAMES
        OutdoorPeopleDetectorImplFactory.hpp
      PATH_SUFFIXES
        ${KMSOUTDOORPEOPLEDETECTOR_BINARY_DIR_PREFIX}/src/server/implementation/generated-cpp
        kurento/modules/outdoorpeopledetector
    )
  endif ()

  list (APPEND KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS ${KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_INTERNAL_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_INTERNAL_INCLUDE_DIR)
endif ()

if (NOT "OutdoorPeopleDetectorOpenCVImpl.hpp OutdoorPeopleDetectorImpl.hpp" STREQUAL "")
  if (TARGET kmsoutdoorpeopledetectorimpl)
    set (KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_GENERATED_INCLUDE_DIR "${KMSOUTDOORPEOPLEDETECTOR_SOURCE_DIR_PREFIX}/src/server/implementation/objects")
  else ()
    find_path(KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_GENERATED_INCLUDE_DIR
      NAMES
        OutdoorPeopleDetectorOpenCVImpl.hpp OutdoorPeopleDetectorImpl.hpp
      PATH_SUFFIXES
        src/server/implementation/objects
        kurento/modules/outdoorpeopledetector
    )
  endif ()

  list (APPEND KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS ${KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_GENERATED_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_GENERATED_INCLUDE_DIR)
endif()

if (NOT "VPDetector.hpp tinyxml2.h" STREQUAL "")
  if (TARGET kmsoutdoorpeopledetectorimpl)
    set (KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_EXTRA_INCLUDE_DIR "${KMSOUTDOORPEOPLEDETECTOR_SOURCE_DIR_PREFIX}/src/server/")
  else ()
    find_path(KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_EXTRA_INCLUDE_DIR
      NAMES
        VPDetector.hpp tinyxml2.h
      PATH_SUFFIXES
        src/server/
        kurento/modules/outdoorpeopledetector
    )
  endif ()

  list (APPEND KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS ${KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_EXTRA_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_EXTRA_INCLUDE_DIR)
endif ()

if (NOT "" STREQUAL "")
  if (TARGET kmsoutdoorpeopledetectorinterface)
    set (KMSOUTDOORPEOPLEDETECTOR_INTERFACE_EXTRA_INCLUDE_DIR "${KMSOUTDOORPEOPLEDETECTOR_SOURCE_DIR_PREFIX}/")
  else ()
    find_path(KMSOUTDOORPEOPLEDETECTOR_INTERFACE_EXTRA_INCLUDE_DIR
      NAMES
        
      PATH_SUFFIXES
        
        kurento/modules/outdoorpeopledetector
    )
  endif()

  list (APPEND KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS ${KMSOUTDOORPEOPLEDETECTOR_INTERFACE_EXTRA_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOUTDOORPEOPLEDETECTOR_INTERFACE_EXTRA_INCLUDE_DIR)
endif ()

if (TARGET kmsoutdoorpeopledetectorimpl)
  set (KMSOUTDOORPEOPLEDETECTOR_LIBRARY kmsoutdoorpeopledetectorimpl)
else ()
  find_library (KMSOUTDOORPEOPLEDETECTOR_LIBRARY
    NAMES
      kmsoutdoorpeopledetectorimpl
    PATH_SUFFIXES
      ${KMSOUTDOORPEOPLEDETECTOR_BINARY_DIR_PREFIX}/src/server
  )
endif()

set (REQUIRED_LIBS "")
foreach (LIB ${REQUIRED_LIBS})
  string(FIND ${LIB} " " POS)

  if (${POS} GREATER 0)
    string(REPLACE " " ";" REQUIRED_LIB_LIST ${LIB})
    include (CMakeParseArguments)
    cmake_parse_arguments("PARAM" "" "LIBNAME" "" ${REQUIRED_LIB_LIST})

    if (DEFINED PARAM_LIBNAME)
      generic_find (${REQUIRED_LIB_LIST} REQUIRED)
      set (LIB_NAME ${PARAM_LIBNAME})
    else()
      string (SUBSTRING ${LIB} 0 ${POS} LIB_NAME)
      string (SUBSTRING ${LIB} ${POS} -1 LIB_VERSION)
      string (STRIP ${LIB_NAME} LIB_NAME)
      string (STRIP ${LIB_VERSION} LIB_VERSION)
      generic_find (LIBNAME ${LIB_NAME} REQUIRED VERSION "${LIB_VERSION}")
    endif()
  else ()
    string (STRIP ${LIB} LIB_NAME)
    generic_find (LIBNAME ${LIB_NAME} REQUIRED)
  endif ()
  list (APPEND REQUIRED_LIBRARIES ${${LIB_NAME}_LIBRARIES})
  list (APPEND KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS ${${LIB_NAME}_INCLUDE_DIRS})

endforeach()

set(KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS
  ${KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS}
  CACHE INTERNAL "Include directories for KMSOUTDOORPEOPLEDETECTOR library" FORCE
)

set (KMSOUTDOORPEOPLEDETECTOR_LIBRARIES
  ${KMSOUTDOORPEOPLEDETECTOR_LIBRARY}
  ${KMSCORE_LIBRARIES}
  ${KMSELEMENTS_LIBRARIES}
  ${KMSFILTERS_LIBRARIES}
  ${REQUIRED_LIBRARIES}
  CACHE INTERNAL "Libraries for KMSOUTDOORPEOPLEDETECTOR" FORCE
)

include (FindPackageHandleStandardArgs)

find_package_handle_standard_args(KMSOUTDOORPEOPLEDETECTOR
  FOUND_VAR
    KMSOUTDOORPEOPLEDETECTOR_FOUND
  REQUIRED_VARS
    ${REQUIRED_VARS}
  VERSION_VAR
    KMSOUTDOORPEOPLEDETECTOR_VERSION
)

mark_as_advanced(
  KMSOUTDOORPEOPLEDETECTOR_FOUND
  KMSOUTDOORPEOPLEDETECTOR_VERSION
  KMSOUTDOORPEOPLEDETECTOR_INTERFACE_INCLUDE_DIR
  KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_INTERNAL_INCLUDE_DIR
  KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_GENERATED_INCLUDE_DIR
  KMSOUTDOORPEOPLEDETECTOR_IMPLEMENTATION_EXTRA_INCLUDE_DIR
  KMSOUTDOORPEOPLEDETECTOR_INTERFACE_EXTRA_INCLUDE_DIR
  KMSOUTDOORPEOPLEDETECTOR_INCLUDE_DIRS
  KMSOUTDOORPEOPLEDETECTOR_LIBRARY
  KMSOUTDOORPEOPLEDETECTOR_LIBRARIES
)
