/* Autogenerated with kurento-module-creator */

#ifndef __INDOOR_PEOPLE_DETECTOR_IMPL_FACTORY_HPP__
#define __INDOOR_PEOPLE_DETECTOR_IMPL_FACTORY_HPP__

#include "IndoorPeopleDetectorImpl.hpp"
#include "OpenCVFilterImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace indoorpeopledetector
{

class IndoorPeopleDetectorImplFactory : public virtual OpenCVFilterImplFactory
{
public:
  IndoorPeopleDetectorImplFactory () {};

  virtual std::string getName () const {
    return "IndoorPeopleDetector";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* indoorpeopledetector */
} /* module */
} /* kurento */

#endif /*  __INDOOR_PEOPLE_DETECTOR_IMPL_FACTORY_HPP__ */