/* Autogenerated with kurento-module-creator */

#ifndef __INDOOR_PEOPLE_DETECTOR_INTERNAL_HPP__
#define __INDOOR_PEOPLE_DETECTOR_INTERNAL_HPP__

#include "IndoorPeopleDetector.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace indoorpeopledetector
{

class IndoorPeopleDetectorMethodSetDB
{
public:
  IndoorPeopleDetectorMethodSetDB() {}
  ~IndoorPeopleDetectorMethodSetDB() {}

  void invoke (std::shared_ptr<IndoorPeopleDetector> obj);
  void Serialize (JsonSerializer &serializer);

  std::string getDb () {
    return db;
  }

  void setDb (const std::string &db) {
    this->db = db;
  }

private:
  std::string db;
};

class IndoorPeopleDetectorMethodSetConfiguration
{
public:
  IndoorPeopleDetectorMethodSetConfiguration() {}
  ~IndoorPeopleDetectorMethodSetConfiguration() {}

  void invoke (std::shared_ptr<IndoorPeopleDetector> obj);
  void Serialize (JsonSerializer &serializer);

  std::string getFile () {
    return file;
  }

  void setFile (const std::string &file) {
    this->file = file;
  }

private:
  std::string file;
};

class IndoorPeopleDetectorConstructor
{
public:
  IndoorPeopleDetectorConstructor () {}
  ~IndoorPeopleDetectorConstructor () {}

  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaPipeline> getMediaPipeline ();

  void setMediaPipeline (std::shared_ptr<MediaPipeline> mediaPipeline) {
    this->mediaPipeline = mediaPipeline;
  }

private:
  std::shared_ptr<MediaPipeline> mediaPipeline;
};

} /* indoorpeopledetector */
} /* module */
} /* kurento */

#endif /*  __INDOOR_PEOPLE_DETECTOR_INTERNAL_HPP__ */
