/* Autogenerated with kurento-module-creator */

#ifndef __INDOOR_PEOPLE_DETECTOR_HPP__
#define __INDOOR_PEOPLE_DETECTOR_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "OpenCVFilter.hpp"

namespace kurento
{
namespace module
{
namespace indoorpeopledetector
{
class IndoorPeopleDetector;
} /* indoorpeopledetector */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::indoorpeopledetector::IndoorPeopleDetector> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace indoorpeopledetector
{
class IndoorPeopleDetector : public virtual OpenCVFilter
{

public:
  IndoorPeopleDetector () {};
  virtual ~IndoorPeopleDetector () {};

  virtual void setDB (const std::string &db) = 0;
  virtual void setConfiguration (const std::string &file) = 0;

  virtual const std::string& getType () const;
  virtual const std::string& getQualifiedType () const;
  virtual const std::string& getModule () const;
  virtual const std::vector<std::string>& getHierarchy () const;

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* indoorpeopledetector */
} /* module */
} /* kurento */

#endif /*  __INDOOR_PEOPLE_DETECTOR_HPP__ */
