/* Autogenerated with kurento-module-creator */

#include "IndoorPeopleDetector.hpp"
#include <mutex>

namespace kurento
{
namespace module
{
namespace indoorpeopledetector
{

static std::vector<std::string> hierarchyIndoorPeopleDetector;
std::once_flag initFlagIndoorPeopleDetector;

static void
initHierarchy ()
{
  hierarchyIndoorPeopleDetector.push_back("kurento.OpenCVFilter");
  hierarchyIndoorPeopleDetector.push_back("kurento.Filter");
  hierarchyIndoorPeopleDetector.push_back("kurento.MediaElement");
  hierarchyIndoorPeopleDetector.push_back("kurento.MediaObject");
}

const std::vector<std::string> &
IndoorPeopleDetector::getHierarchy () const
{
  std::call_once (initFlagIndoorPeopleDetector,initHierarchy);
  return hierarchyIndoorPeopleDetector;
}

const std::string&
IndoorPeopleDetector::getType () const {
  static std::string typeName = "IndoorPeopleDetector";

  return typeName;
}

const std::string&
IndoorPeopleDetector::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
IndoorPeopleDetector::getModule () const {
  static std::string moduleName =  "indoorpeopledetector";

  return moduleName;
}

} /* indoorpeopledetector */
} /* module */
} /* kurento */
