/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <RecorderByMovementImplFactory.hpp>
#include "RecorderByMovementImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>
#include "MediaPipelineImpl.hpp"

#define GST_CAT_DEFAULT kurento_recorder_by_movement_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentoRecorderByMovementImpl"

namespace kurento
{
namespace module
{
namespace recorderbymovement
{

RecorderByMovementImpl::RecorderByMovementImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) : OpenCVFilterImpl (config, std::dynamic_pointer_cast<MediaPipelineImpl> (mediaPipeline) )

{
}

void RecorderByMovementImpl::loadConfig(const std::string &file)
{
  RecorderByMovementOpenCVImpl::loadConfig(file);
}

MediaObjectImpl *
RecorderByMovementImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new RecorderByMovementImpl (config, mediaPipeline);
}

RecorderByMovementImpl::StaticConstructor RecorderByMovementImpl::staticConstructor;

RecorderByMovementImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* recorderbymovement */
} /* module */
} /* kurento */
