/* Autogenerated with kurento-module-creator */

#ifndef __RECORDER_BY_MOVEMENT_IMPL_HPP__
#define __RECORDER_BY_MOVEMENT_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "RecorderByMovement.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "RecorderByMovementOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace recorderbymovement
{
class RecorderByMovementImpl;
} /* recorderbymovement */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::recorderbymovement::RecorderByMovementImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace recorderbymovement
{

class RecorderByMovementImpl : public OpenCVFilterImpl, public virtual RecorderByMovement, public virtual RecorderByMovementOpenCVImpl
{

public:

  RecorderByMovementImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~RecorderByMovementImpl () {};

  void loadConfig (const std::string &file);

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* recorderbymovement */
} /* module */
} /* kurento */

#endif /*  __RECORDER_BY_MOVEMENT_IMPL_HPP__ */
