/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "RecorderByMovementImpl.hpp"
#include "RecorderByMovementImplFactory.hpp"
#include "RecorderByMovementInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{
namespace module
{
namespace recorderbymovement
{

MediaObjectImpl *RecorderByMovementImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  RecorderByMovementConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
RecorderByMovementImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "loadConfig") {
    kurento::JsonSerializer s (false);
    RecorderByMovementMethodLoadConfig method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<RecorderByMovement> (obj) );
    return;
  }

  OpenCVFilterImpl::invoke (obj, methodName, params, response);
}

bool
RecorderByMovementImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return OpenCVFilterImpl::connect (eventType, handler);
}

void
RecorderByMovementImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'RecorderByMovementImpl' cannot be deserialized as an object");
  }
}
} /* recorderbymovement */
} /* module */
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::module::recorderbymovement::RecorderByMovementImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::module::recorderbymovement::RecorderByMovementImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::module::recorderbymovement::RecorderByMovementImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::module::recorderbymovement::RecorderByMovement> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::module::recorderbymovement::RecorderByMovementImpl> aux = std::dynamic_pointer_cast<kurento::module::recorderbymovement::RecorderByMovementImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::module::recorderbymovement::RecorderByMovement> (aux);
}

} /* kurento */