/* Autogenerated with kurento-module-creator */

#include "RecorderByMovementImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace recorderbymovement
{

void dummyRecorderbymovement ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<RecorderByMovement> object;

    s.SerializeNVP (object);
  }
}

} /* recorderbymovement */
} /* module */
} /* kurento */
