/* Autogenerated with kurento-module-creator */

#ifndef __SUBSENSE_HPP__
#define __SUBSENSE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "OpenCVFilter.hpp"

namespace kurento
{
namespace module
{
namespace subsense
{
class Subsense;
} /* subsense */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::subsense::Subsense> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace subsense
{
class Subsense : public virtual OpenCVFilter
{

public:
  Subsense () {};
  virtual ~Subsense () {};

  virtual const std::string& getType () const;
  virtual const std::string& getQualifiedType () const;
  virtual const std::string& getModule () const;
  virtual const std::vector<std::string>& getHierarchy () const;

  virtual void Serialize (JsonSerializer &serializer) = 0;

};

} /* subsense */
} /* module */
} /* kurento */

#endif /*  __SUBSENSE_HPP__ */
