/* Autogenerated with kurento-module-creator */

#include "Subsense.hpp"
#include <mutex>

namespace kurento
{
namespace module
{
namespace subsense
{

static std::vector<std::string> hierarchySubsense;
std::once_flag initFlagSubsense;

static void
initHierarchy ()
{
  hierarchySubsense.push_back("kurento.OpenCVFilter");
  hierarchySubsense.push_back("kurento.Filter");
  hierarchySubsense.push_back("kurento.MediaElement");
  hierarchySubsense.push_back("kurento.MediaObject");
}

const std::vector<std::string> &
Subsense::getHierarchy () const
{
  std::call_once (initFlagSubsense,initHierarchy);
  return hierarchySubsense;
}

const std::string&
Subsense::getType () const {
  static std::string typeName = "Subsense";

  return typeName;
}

const std::string&
Subsense::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
Subsense::getModule () const {
  static std::string moduleName =  "subsense";

  return moduleName;
}

} /* subsense */
} /* module */
} /* kurento */
