/* Autogenerated with kurento-module-creator */

#ifndef __SUBSENSE_INTERNAL_HPP__
#define __SUBSENSE_INTERNAL_HPP__

#include "Subsense.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace subsense
{

class SubsenseConstructor
{
public:
  SubsenseConstructor () {}
  ~SubsenseConstructor () {}

  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaPipeline> getMediaPipeline ();

  void setMediaPipeline (std::shared_ptr<MediaPipeline> mediaPipeline) {
    this->mediaPipeline = mediaPipeline;
  }

private:
  std::shared_ptr<MediaPipeline> mediaPipeline;
};

} /* subsense */
} /* module */
} /* kurento */

#endif /*  __SUBSENSE_INTERNAL_HPP__ */
